/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FragmentEntryPropagation service. Represents a row in the &quot;FragmentEntryPropagation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.fragment.model.impl.FragmentEntryPropagationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.fragment.model.impl.FragmentEntryPropagationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentEntryPropagation
 * @generated
 */
@ProviderType
public interface FragmentEntryPropagationModel
	extends BaseModel<FragmentEntryPropagation>,
			CTModel<FragmentEntryPropagation>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fragment entry propagation model instance should use the {@link FragmentEntryPropagation} interface instead.
	 */

	/**
	 * Returns the primary key of this fragment entry propagation.
	 *
	 * @return the primary key of this fragment entry propagation
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fragment entry propagation.
	 *
	 * @param primaryKey the primary key of this fragment entry propagation
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this fragment entry propagation.
	 *
	 * @return the mvcc version of this fragment entry propagation
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this fragment entry propagation.
	 *
	 * @param mvccVersion the mvcc version of this fragment entry propagation
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this fragment entry propagation.
	 *
	 * @return the ct collection ID of this fragment entry propagation
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this fragment entry propagation.
	 *
	 * @param ctCollectionId the ct collection ID of this fragment entry propagation
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the fragment entry propagation ID of this fragment entry propagation.
	 *
	 * @return the fragment entry propagation ID of this fragment entry propagation
	 */
	public long getFragmentEntryPropagationId();

	/**
	 * Sets the fragment entry propagation ID of this fragment entry propagation.
	 *
	 * @param fragmentEntryPropagationId the fragment entry propagation ID of this fragment entry propagation
	 */
	public void setFragmentEntryPropagationId(long fragmentEntryPropagationId);

	/**
	 * Returns the create date of this fragment entry propagation.
	 *
	 * @return the create date of this fragment entry propagation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fragment entry propagation.
	 *
	 * @param createDate the create date of this fragment entry propagation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fragment entry propagation.
	 *
	 * @return the modified date of this fragment entry propagation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fragment entry propagation.
	 *
	 * @param modifiedDate the modified date of this fragment entry propagation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fragment entry key of this fragment entry propagation.
	 *
	 * @return the fragment entry key of this fragment entry propagation
	 */
	@AutoEscape
	public String getFragmentEntryKey();

	/**
	 * Sets the fragment entry key of this fragment entry propagation.
	 *
	 * @param fragmentEntryKey the fragment entry key of this fragment entry propagation
	 */
	public void setFragmentEntryKey(String fragmentEntryKey);

	/**
	 * Returns the css of this fragment entry propagation.
	 *
	 * @return the css of this fragment entry propagation
	 */
	@AutoEscape
	public String getCss();

	/**
	 * Sets the css of this fragment entry propagation.
	 *
	 * @param css the css of this fragment entry propagation
	 */
	public void setCss(String css);

	/**
	 * Returns the html of this fragment entry propagation.
	 *
	 * @return the html of this fragment entry propagation
	 */
	@AutoEscape
	public String getHtml();

	/**
	 * Sets the html of this fragment entry propagation.
	 *
	 * @param html the html of this fragment entry propagation
	 */
	public void setHtml(String html);

	/**
	 * Returns the js of this fragment entry propagation.
	 *
	 * @return the js of this fragment entry propagation
	 */
	@AutoEscape
	public String getJs();

	/**
	 * Sets the js of this fragment entry propagation.
	 *
	 * @param js the js of this fragment entry propagation
	 */
	public void setJs(String js);

	/**
	 * Returns the configuration of this fragment entry propagation.
	 *
	 * @return the configuration of this fragment entry propagation
	 */
	@AutoEscape
	public String getConfiguration();

	/**
	 * Sets the configuration of this fragment entry propagation.
	 *
	 * @param configuration the configuration of this fragment entry propagation
	 */
	public void setConfiguration(String configuration);

	/**
	 * Returns the type of this fragment entry propagation.
	 *
	 * @return the type of this fragment entry propagation
	 */
	public int getType();

	/**
	 * Sets the type of this fragment entry propagation.
	 *
	 * @param type the type of this fragment entry propagation
	 */
	public void setType(int type);

	@Override
	public FragmentEntryPropagation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}