include-and-override=portlet-ext.properties
resource.actions.configs=resource-actions/default.xml
#
# Set the location of the default content for each language type.
#
templates.template.language.content[ftl]=com/liferay/templates/web/dependencies/template.ftl
templates.template.language.content[vm]=com/liferay/templates/web/dependencies/template.vm
templates.template.language.content[xsl]=com/liferay/templates/web/dependencies/template.xsl

#
# Input a list of comma delimited resource action configurations that will be
# read from the class path.
#