/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.seo.service.base;

import com.liferay.layout.seo.model.LayoutSEOEntryCustomMetaTag;
import com.liferay.layout.seo.service.LayoutSEOEntryCustomMetaTagLocalService;
import com.liferay.layout.seo.service.persistence.LayoutSEOEntryCustomMetaTagPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout seo entry custom meta tag local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.seo.service.impl.LayoutSEOEntryCustomMetaTagLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.seo.service.impl.LayoutSEOEntryCustomMetaTagLocalServiceImpl
 * @generated
 */
public abstract class LayoutSEOEntryCustomMetaTagLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   LayoutSEOEntryCustomMetaTagLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LayoutSEOEntryCustomMetaTagLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.layout.seo.service.LayoutSEOEntryCustomMetaTagLocalServiceUtil</code>.
	 */

	/**
	 * Adds the layout seo entry custom meta tag to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutSEOEntryCustomMetaTagLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutSEOEntryCustomMetaTag the layout seo entry custom meta tag
	 * @return the layout seo entry custom meta tag that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutSEOEntryCustomMetaTag addLayoutSEOEntryCustomMetaTag(
		LayoutSEOEntryCustomMetaTag layoutSEOEntryCustomMetaTag) {

		layoutSEOEntryCustomMetaTag.setNew(true);

		return layoutSEOEntryCustomMetaTagPersistence.update(
			layoutSEOEntryCustomMetaTag);
	}

	/**
	 * Creates a new layout seo entry custom meta tag with the primary key. Does not add the layout seo entry custom meta tag to the database.
	 *
	 * @param layoutSEOEntryCustomMetaTagId the primary key for the new layout seo entry custom meta tag
	 * @return the new layout seo entry custom meta tag
	 */
	@Override
	@Transactional(enabled = false)
	public LayoutSEOEntryCustomMetaTag createLayoutSEOEntryCustomMetaTag(
		long layoutSEOEntryCustomMetaTagId) {

		return layoutSEOEntryCustomMetaTagPersistence.create(
			layoutSEOEntryCustomMetaTagId);
	}

	/**
	 * Deletes the layout seo entry custom meta tag with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutSEOEntryCustomMetaTagLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutSEOEntryCustomMetaTagId the primary key of the layout seo entry custom meta tag
	 * @return the layout seo entry custom meta tag that was removed
	 * @throws PortalException if a layout seo entry custom meta tag with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutSEOEntryCustomMetaTag deleteLayoutSEOEntryCustomMetaTag(
			long layoutSEOEntryCustomMetaTagId)
		throws PortalException {

		return layoutSEOEntryCustomMetaTagPersistence.remove(
			layoutSEOEntryCustomMetaTagId);
	}

	/**
	 * Deletes the layout seo entry custom meta tag from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutSEOEntryCustomMetaTagLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutSEOEntryCustomMetaTag the layout seo entry custom meta tag
	 * @return the layout seo entry custom meta tag that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutSEOEntryCustomMetaTag deleteLayoutSEOEntryCustomMetaTag(
		LayoutSEOEntryCustomMetaTag layoutSEOEntryCustomMetaTag) {

		return layoutSEOEntryCustomMetaTagPersistence.remove(
			layoutSEOEntryCustomMetaTag);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return layoutSEOEntryCustomMetaTagPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LayoutSEOEntryCustomMetaTag.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return layoutSEOEntryCustomMetaTagPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOEntryCustomMetaTagModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return layoutSEOEntryCustomMetaTagPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOEntryCustomMetaTagModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return layoutSEOEntryCustomMetaTagPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return layoutSEOEntryCustomMetaTagPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return layoutSEOEntryCustomMetaTagPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LayoutSEOEntryCustomMetaTag fetchLayoutSEOEntryCustomMetaTag(
		long layoutSEOEntryCustomMetaTagId) {

		return layoutSEOEntryCustomMetaTagPersistence.fetchByPrimaryKey(
			layoutSEOEntryCustomMetaTagId);
	}

	/**
	 * Returns the layout seo entry custom meta tag with the primary key.
	 *
	 * @param layoutSEOEntryCustomMetaTagId the primary key of the layout seo entry custom meta tag
	 * @return the layout seo entry custom meta tag
	 * @throws PortalException if a layout seo entry custom meta tag with the primary key could not be found
	 */
	@Override
	public LayoutSEOEntryCustomMetaTag getLayoutSEOEntryCustomMetaTag(
			long layoutSEOEntryCustomMetaTagId)
		throws PortalException {

		return layoutSEOEntryCustomMetaTagPersistence.findByPrimaryKey(
			layoutSEOEntryCustomMetaTagId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			layoutSEOEntryCustomMetaTagLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutSEOEntryCustomMetaTag.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutSEOEntryCustomMetaTagId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			layoutSEOEntryCustomMetaTagLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LayoutSEOEntryCustomMetaTag.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutSEOEntryCustomMetaTagId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			layoutSEOEntryCustomMetaTagLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LayoutSEOEntryCustomMetaTag.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutSEOEntryCustomMetaTagId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutSEOEntryCustomMetaTagPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement LayoutSEOEntryCustomMetaTagLocalServiceImpl#deleteLayoutSEOEntryCustomMetaTag(LayoutSEOEntryCustomMetaTag) to avoid orphaned data");
		}

		return layoutSEOEntryCustomMetaTagLocalService.
			deleteLayoutSEOEntryCustomMetaTag(
				(LayoutSEOEntryCustomMetaTag)persistedModel);
	}

	@Override
	public BasePersistence<LayoutSEOEntryCustomMetaTag> getBasePersistence() {
		return layoutSEOEntryCustomMetaTagPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutSEOEntryCustomMetaTagPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the layout seo entry custom meta tags.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.seo.model.impl.LayoutSEOEntryCustomMetaTagModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of layout seo entry custom meta tags
	 * @param end the upper bound of the range of layout seo entry custom meta tags (not inclusive)
	 * @return the range of layout seo entry custom meta tags
	 */
	@Override
	public List<LayoutSEOEntryCustomMetaTag> getLayoutSEOEntryCustomMetaTags(
		int start, int end) {

		return layoutSEOEntryCustomMetaTagPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of layout seo entry custom meta tags.
	 *
	 * @return the number of layout seo entry custom meta tags
	 */
	@Override
	public int getLayoutSEOEntryCustomMetaTagsCount() {
		return layoutSEOEntryCustomMetaTagPersistence.countAll();
	}

	/**
	 * Updates the layout seo entry custom meta tag in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutSEOEntryCustomMetaTagLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutSEOEntryCustomMetaTag the layout seo entry custom meta tag
	 * @return the layout seo entry custom meta tag that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutSEOEntryCustomMetaTag updateLayoutSEOEntryCustomMetaTag(
		LayoutSEOEntryCustomMetaTag layoutSEOEntryCustomMetaTag) {

		return layoutSEOEntryCustomMetaTagPersistence.update(
			layoutSEOEntryCustomMetaTag);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LayoutSEOEntryCustomMetaTagLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		layoutSEOEntryCustomMetaTagLocalService =
			(LayoutSEOEntryCustomMetaTagLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutSEOEntryCustomMetaTagLocalService.class.getName();
	}

	@Override
	public CTPersistence<LayoutSEOEntryCustomMetaTag> getCTPersistence() {
		return layoutSEOEntryCustomMetaTagPersistence;
	}

	@Override
	public Class<LayoutSEOEntryCustomMetaTag> getModelClass() {
		return LayoutSEOEntryCustomMetaTag.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<LayoutSEOEntryCustomMetaTag>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			layoutSEOEntryCustomMetaTagPersistence);
	}

	protected String getModelClassName() {
		return LayoutSEOEntryCustomMetaTag.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			layoutSEOEntryCustomMetaTagPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected LayoutSEOEntryCustomMetaTagLocalService
		layoutSEOEntryCustomMetaTagLocalService;

	@Reference
	protected LayoutSEOEntryCustomMetaTagPersistence
		layoutSEOEntryCustomMetaTagPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		LayoutSEOEntryCustomMetaTagLocalServiceBaseImpl.class);

}