/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.fragment.model.FragmentEntryPropagation;
import com.liferay.fragment.model.FragmentEntryPropagationModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FragmentEntryPropagation service. Represents a row in the &quot;FragmentEntryPropagation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FragmentEntryPropagationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FragmentEntryPropagationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentEntryPropagationImpl
 * @generated
 */
public class FragmentEntryPropagationModelImpl
	extends BaseModelImpl<FragmentEntryPropagation>
	implements FragmentEntryPropagationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fragment entry propagation model instance should use the <code>FragmentEntryPropagation</code> interface instead.
	 */
	public static final String TABLE_NAME = "FragmentEntryPropagation";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"fragmentEntryPropagationId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fragmentEntryKey", Types.VARCHAR}, {"css", Types.CLOB},
		{"html", Types.CLOB}, {"js", Types.CLOB}, {"configuration", Types.CLOB},
		{"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryPropagationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fragmentEntryKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("css", Types.CLOB);
		TABLE_COLUMNS_MAP.put("html", Types.CLOB);
		TABLE_COLUMNS_MAP.put("js", Types.CLOB);
		TABLE_COLUMNS_MAP.put("configuration", Types.CLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FragmentEntryPropagation (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,fragmentEntryPropagationId LONG not null,createDate DATE null,modifiedDate DATE null,fragmentEntryKey VARCHAR(75) null,css TEXT null,html TEXT null,js TEXT null,configuration TEXT null,type_ INTEGER,primary key (fragmentEntryPropagationId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table FragmentEntryPropagation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fragmentEntryPropagation.fragmentEntryPropagationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FragmentEntryPropagation.fragmentEntryPropagationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRAGMENTENTRYKEY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRAGMENTENTRYPROPAGATIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FragmentEntryPropagationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fragmentEntryPropagationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFragmentEntryPropagationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fragmentEntryPropagationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FragmentEntryPropagation.class;
	}

	@Override
	public String getModelClassName() {
		return FragmentEntryPropagation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FragmentEntryPropagation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FragmentEntryPropagation, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FragmentEntryPropagation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FragmentEntryPropagation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FragmentEntryPropagation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FragmentEntryPropagation, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FragmentEntryPropagation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FragmentEntryPropagation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FragmentEntryPropagation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FragmentEntryPropagation, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<FragmentEntryPropagation, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<FragmentEntryPropagation, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FragmentEntryPropagation, Object>>();
		Map<String, BiConsumer<FragmentEntryPropagation, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FragmentEntryPropagation, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FragmentEntryPropagation::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FragmentEntryPropagation, Long>)
				FragmentEntryPropagation::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", FragmentEntryPropagation::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<FragmentEntryPropagation, Long>)
				FragmentEntryPropagation::setCtCollectionId);
		attributeGetterFunctions.put(
			"fragmentEntryPropagationId",
			FragmentEntryPropagation::getFragmentEntryPropagationId);
		attributeSetterBiConsumers.put(
			"fragmentEntryPropagationId",
			(BiConsumer<FragmentEntryPropagation, Long>)
				FragmentEntryPropagation::setFragmentEntryPropagationId);
		attributeGetterFunctions.put(
			"createDate", FragmentEntryPropagation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FragmentEntryPropagation, Date>)
				FragmentEntryPropagation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FragmentEntryPropagation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FragmentEntryPropagation, Date>)
				FragmentEntryPropagation::setModifiedDate);
		attributeGetterFunctions.put(
			"fragmentEntryKey", FragmentEntryPropagation::getFragmentEntryKey);
		attributeSetterBiConsumers.put(
			"fragmentEntryKey",
			(BiConsumer<FragmentEntryPropagation, String>)
				FragmentEntryPropagation::setFragmentEntryKey);
		attributeGetterFunctions.put("css", FragmentEntryPropagation::getCss);
		attributeSetterBiConsumers.put(
			"css",
			(BiConsumer<FragmentEntryPropagation, String>)
				FragmentEntryPropagation::setCss);
		attributeGetterFunctions.put("html", FragmentEntryPropagation::getHtml);
		attributeSetterBiConsumers.put(
			"html",
			(BiConsumer<FragmentEntryPropagation, String>)
				FragmentEntryPropagation::setHtml);
		attributeGetterFunctions.put("js", FragmentEntryPropagation::getJs);
		attributeSetterBiConsumers.put(
			"js",
			(BiConsumer<FragmentEntryPropagation, String>)
				FragmentEntryPropagation::setJs);
		attributeGetterFunctions.put(
			"configuration", FragmentEntryPropagation::getConfiguration);
		attributeSetterBiConsumers.put(
			"configuration",
			(BiConsumer<FragmentEntryPropagation, String>)
				FragmentEntryPropagation::setConfiguration);
		attributeGetterFunctions.put("type", FragmentEntryPropagation::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<FragmentEntryPropagation, Integer>)
				FragmentEntryPropagation::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getFragmentEntryPropagationId() {
		return _fragmentEntryPropagationId;
	}

	@Override
	public void setFragmentEntryPropagationId(long fragmentEntryPropagationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fragmentEntryPropagationId = fragmentEntryPropagationId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFragmentEntryKey() {
		if (_fragmentEntryKey == null) {
			return "";
		}
		else {
			return _fragmentEntryKey;
		}
	}

	@Override
	public void setFragmentEntryKey(String fragmentEntryKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fragmentEntryKey = fragmentEntryKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFragmentEntryKey() {
		return getColumnOriginalValue("fragmentEntryKey");
	}

	@Override
	public String getCss() {
		if (_css == null) {
			return "";
		}
		else {
			return _css;
		}
	}

	@Override
	public void setCss(String css) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_css = css;
	}

	@Override
	public String getHtml() {
		if (_html == null) {
			return "";
		}
		else {
			return _html;
		}
	}

	@Override
	public void setHtml(String html) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_html = html;
	}

	@Override
	public String getJs() {
		if (_js == null) {
			return "";
		}
		else {
			return _js;
		}
	}

	@Override
	public void setJs(String js) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_js = js;
	}

	@Override
	public String getConfiguration() {
		if (_configuration == null) {
			return "";
		}
		else {
			return _configuration;
		}
	}

	@Override
	public void setConfiguration(String configuration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_configuration = configuration;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FragmentEntryPropagation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FragmentEntryPropagation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FragmentEntryPropagation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FragmentEntryPropagationImpl fragmentEntryPropagationImpl =
			new FragmentEntryPropagationImpl();

		fragmentEntryPropagationImpl.setMvccVersion(getMvccVersion());
		fragmentEntryPropagationImpl.setCtCollectionId(getCtCollectionId());
		fragmentEntryPropagationImpl.setFragmentEntryPropagationId(
			getFragmentEntryPropagationId());
		fragmentEntryPropagationImpl.setCreateDate(getCreateDate());
		fragmentEntryPropagationImpl.setModifiedDate(getModifiedDate());
		fragmentEntryPropagationImpl.setFragmentEntryKey(getFragmentEntryKey());
		fragmentEntryPropagationImpl.setCss(getCss());
		fragmentEntryPropagationImpl.setHtml(getHtml());
		fragmentEntryPropagationImpl.setJs(getJs());
		fragmentEntryPropagationImpl.setConfiguration(getConfiguration());
		fragmentEntryPropagationImpl.setType(getType());

		fragmentEntryPropagationImpl.resetOriginalValues();

		return fragmentEntryPropagationImpl;
	}

	@Override
	public FragmentEntryPropagation cloneWithOriginalValues() {
		FragmentEntryPropagationImpl fragmentEntryPropagationImpl =
			new FragmentEntryPropagationImpl();

		fragmentEntryPropagationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fragmentEntryPropagationImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		fragmentEntryPropagationImpl.setFragmentEntryPropagationId(
			this.<Long>getColumnOriginalValue("fragmentEntryPropagationId"));
		fragmentEntryPropagationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fragmentEntryPropagationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fragmentEntryPropagationImpl.setFragmentEntryKey(
			this.<String>getColumnOriginalValue("fragmentEntryKey"));
		fragmentEntryPropagationImpl.setCss(
			this.<String>getColumnOriginalValue("css"));
		fragmentEntryPropagationImpl.setHtml(
			this.<String>getColumnOriginalValue("html"));
		fragmentEntryPropagationImpl.setJs(
			this.<String>getColumnOriginalValue("js"));
		fragmentEntryPropagationImpl.setConfiguration(
			this.<String>getColumnOriginalValue("configuration"));
		fragmentEntryPropagationImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));

		return fragmentEntryPropagationImpl;
	}

	@Override
	public int compareTo(FragmentEntryPropagation fragmentEntryPropagation) {
		long primaryKey = fragmentEntryPropagation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FragmentEntryPropagation)) {
			return false;
		}

		FragmentEntryPropagation fragmentEntryPropagation =
			(FragmentEntryPropagation)object;

		long primaryKey = fragmentEntryPropagation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FragmentEntryPropagation> toCacheModel() {
		FragmentEntryPropagationCacheModel fragmentEntryPropagationCacheModel =
			new FragmentEntryPropagationCacheModel();

		fragmentEntryPropagationCacheModel.mvccVersion = getMvccVersion();

		fragmentEntryPropagationCacheModel.ctCollectionId = getCtCollectionId();

		fragmentEntryPropagationCacheModel.fragmentEntryPropagationId =
			getFragmentEntryPropagationId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			fragmentEntryPropagationCacheModel.createDate =
				createDate.getTime();
		}
		else {
			fragmentEntryPropagationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fragmentEntryPropagationCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			fragmentEntryPropagationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fragmentEntryPropagationCacheModel.fragmentEntryKey =
			getFragmentEntryKey();

		String fragmentEntryKey =
			fragmentEntryPropagationCacheModel.fragmentEntryKey;

		if ((fragmentEntryKey != null) && (fragmentEntryKey.length() == 0)) {
			fragmentEntryPropagationCacheModel.fragmentEntryKey = null;
		}

		fragmentEntryPropagationCacheModel.css = getCss();

		String css = fragmentEntryPropagationCacheModel.css;

		if ((css != null) && (css.length() == 0)) {
			fragmentEntryPropagationCacheModel.css = null;
		}

		fragmentEntryPropagationCacheModel.html = getHtml();

		String html = fragmentEntryPropagationCacheModel.html;

		if ((html != null) && (html.length() == 0)) {
			fragmentEntryPropagationCacheModel.html = null;
		}

		fragmentEntryPropagationCacheModel.js = getJs();

		String js = fragmentEntryPropagationCacheModel.js;

		if ((js != null) && (js.length() == 0)) {
			fragmentEntryPropagationCacheModel.js = null;
		}

		fragmentEntryPropagationCacheModel.configuration = getConfiguration();

		String configuration = fragmentEntryPropagationCacheModel.configuration;

		if ((configuration != null) && (configuration.length() == 0)) {
			fragmentEntryPropagationCacheModel.configuration = null;
		}

		fragmentEntryPropagationCacheModel.type = getType();

		return fragmentEntryPropagationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FragmentEntryPropagation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FragmentEntryPropagation, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FragmentEntryPropagation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FragmentEntryPropagation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FragmentEntryPropagation>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						FragmentEntryPropagation.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _fragmentEntryPropagationId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _fragmentEntryKey;
	private String _css;
	private String _html;
	private String _js;
	private String _configuration;
	private int _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FragmentEntryPropagation, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FragmentEntryPropagation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"fragmentEntryPropagationId", _fragmentEntryPropagationId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fragmentEntryKey", _fragmentEntryKey);
		_columnOriginalValues.put("css", _css);
		_columnOriginalValues.put("html", _html);
		_columnOriginalValues.put("js", _js);
		_columnOriginalValues.put("configuration", _configuration);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("fragmentEntryPropagationId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("fragmentEntryKey", 32L);

		columnBitmasks.put("css", 64L);

		columnBitmasks.put("html", 128L);

		columnBitmasks.put("js", 256L);

		columnBitmasks.put("configuration", 512L);

		columnBitmasks.put("type_", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FragmentEntryPropagation _escapedModel;

}