/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.service.base;

import com.liferay.fragment.model.FragmentEntryPropagation;
import com.liferay.fragment.service.FragmentEntryPropagationLocalService;
import com.liferay.fragment.service.FragmentEntryPropagationLocalServiceUtil;
import com.liferay.fragment.service.persistence.FragmentEntryPropagationPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fragment entry propagation local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.fragment.service.impl.FragmentEntryPropagationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.fragment.service.impl.FragmentEntryPropagationLocalServiceImpl
 * @generated
 */
public abstract class FragmentEntryPropagationLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FragmentEntryPropagationLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FragmentEntryPropagationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FragmentEntryPropagationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the fragment entry propagation to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FragmentEntryPropagationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fragmentEntryPropagation the fragment entry propagation
	 * @return the fragment entry propagation that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FragmentEntryPropagation addFragmentEntryPropagation(
		FragmentEntryPropagation fragmentEntryPropagation) {

		fragmentEntryPropagation.setNew(true);

		return fragmentEntryPropagationPersistence.update(
			fragmentEntryPropagation);
	}

	/**
	 * Creates a new fragment entry propagation with the primary key. Does not add the fragment entry propagation to the database.
	 *
	 * @param fragmentEntryPropagationId the primary key for the new fragment entry propagation
	 * @return the new fragment entry propagation
	 */
	@Override
	@Transactional(enabled = false)
	public FragmentEntryPropagation createFragmentEntryPropagation(
		long fragmentEntryPropagationId) {

		return fragmentEntryPropagationPersistence.create(
			fragmentEntryPropagationId);
	}

	/**
	 * Deletes the fragment entry propagation with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FragmentEntryPropagationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fragmentEntryPropagationId the primary key of the fragment entry propagation
	 * @return the fragment entry propagation that was removed
	 * @throws PortalException if a fragment entry propagation with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FragmentEntryPropagation deleteFragmentEntryPropagation(
			long fragmentEntryPropagationId)
		throws PortalException {

		return fragmentEntryPropagationPersistence.remove(
			fragmentEntryPropagationId);
	}

	/**
	 * Deletes the fragment entry propagation from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FragmentEntryPropagationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fragmentEntryPropagation the fragment entry propagation
	 * @return the fragment entry propagation that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FragmentEntryPropagation deleteFragmentEntryPropagation(
		FragmentEntryPropagation fragmentEntryPropagation) {

		return fragmentEntryPropagationPersistence.remove(
			fragmentEntryPropagation);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return fragmentEntryPropagationPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FragmentEntryPropagation.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fragmentEntryPropagationPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fragment.model.impl.FragmentEntryPropagationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return fragmentEntryPropagationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fragment.model.impl.FragmentEntryPropagationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return fragmentEntryPropagationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fragmentEntryPropagationPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return fragmentEntryPropagationPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FragmentEntryPropagation fetchFragmentEntryPropagation(
		long fragmentEntryPropagationId) {

		return fragmentEntryPropagationPersistence.fetchByPrimaryKey(
			fragmentEntryPropagationId);
	}

	/**
	 * Returns the fragment entry propagation with the primary key.
	 *
	 * @param fragmentEntryPropagationId the primary key of the fragment entry propagation
	 * @return the fragment entry propagation
	 * @throws PortalException if a fragment entry propagation with the primary key could not be found
	 */
	@Override
	public FragmentEntryPropagation getFragmentEntryPropagation(
			long fragmentEntryPropagationId)
		throws PortalException {

		return fragmentEntryPropagationPersistence.findByPrimaryKey(
			fragmentEntryPropagationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			fragmentEntryPropagationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FragmentEntryPropagation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentEntryPropagationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			fragmentEntryPropagationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			FragmentEntryPropagation.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentEntryPropagationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			fragmentEntryPropagationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FragmentEntryPropagation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentEntryPropagationId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fragmentEntryPropagationPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FragmentEntryPropagationLocalServiceImpl#deleteFragmentEntryPropagation(FragmentEntryPropagation) to avoid orphaned data");
		}

		return fragmentEntryPropagationLocalService.
			deleteFragmentEntryPropagation(
				(FragmentEntryPropagation)persistedModel);
	}

	@Override
	public BasePersistence<FragmentEntryPropagation> getBasePersistence() {
		return fragmentEntryPropagationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fragmentEntryPropagationPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the fragment entry propagations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.fragment.model.impl.FragmentEntryPropagationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of fragment entry propagations
	 * @param end the upper bound of the range of fragment entry propagations (not inclusive)
	 * @return the range of fragment entry propagations
	 */
	@Override
	public List<FragmentEntryPropagation> getFragmentEntryPropagations(
		int start, int end) {

		return fragmentEntryPropagationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fragment entry propagations.
	 *
	 * @return the number of fragment entry propagations
	 */
	@Override
	public int getFragmentEntryPropagationsCount() {
		return fragmentEntryPropagationPersistence.countAll();
	}

	/**
	 * Updates the fragment entry propagation in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FragmentEntryPropagationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fragmentEntryPropagation the fragment entry propagation
	 * @return the fragment entry propagation that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FragmentEntryPropagation updateFragmentEntryPropagation(
		FragmentEntryPropagation fragmentEntryPropagation) {

		return fragmentEntryPropagationPersistence.update(
			fragmentEntryPropagation);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FragmentEntryPropagationLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		fragmentEntryPropagationLocalService =
			(FragmentEntryPropagationLocalService)aopProxy;

		_setLocalServiceUtilService(fragmentEntryPropagationLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FragmentEntryPropagationLocalService.class.getName();
	}

	@Override
	public CTPersistence<FragmentEntryPropagation> getCTPersistence() {
		return fragmentEntryPropagationPersistence;
	}

	@Override
	public Class<FragmentEntryPropagation> getModelClass() {
		return FragmentEntryPropagation.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<FragmentEntryPropagation>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(fragmentEntryPropagationPersistence);
	}

	protected String getModelClassName() {
		return FragmentEntryPropagation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				fragmentEntryPropagationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FragmentEntryPropagationLocalService
			fragmentEntryPropagationLocalService) {

		try {
			Field field =
				FragmentEntryPropagationLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, fragmentEntryPropagationLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected FragmentEntryPropagationLocalService
		fragmentEntryPropagationLocalService;

	@Reference
	protected FragmentEntryPropagationPersistence
		fragmentEntryPropagationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		FragmentEntryPropagationLocalServiceBaseImpl.class);

}